version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: 3w-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "33066:3306"

  wordpress:
    image: wordpress:6.6-php8.2-apache
    container_name: 3w-wordpress
    restart: unless-stopped
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_HOME', 'http://localhost:8080' );
        define( 'WP_SITEURL', 'http://localhost:8080' );
        define( 'WP_DEBUG', true );
        define( 'WP_DEBUG_LOG', true );
        define( 'SCRIPT_DEBUG', true );
        if ( getenv('XDEBUG_MODE') ) {
          ini_set( 'xdebug.mode', getenv('XDEBUG_MODE') );
        }
    volumes:
      - wp_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    ports:
      - "8080:80"

  wpcli:
    image: wordpress:cli-php8.2
    container_name: 3w-wpcli
    depends_on:
      - db
      - wordpress
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - wp_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    entrypoint: ["bash", "-lc"]

  mailpit:
    image: axllent/mailpit:v1.18
    container_name: 3w-mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: 3w-phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: ${WORDPRESS_DB_USER}
      PMA_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    ports:
      - "8081:80"

volumes:
  db_data:
  wp_data:
