<?php
/**
 * 3W 2025 Theme bootstrap
 */

if (!defined('ABSPATH')) {
    exit;
}

if (!defined('THREEW_SHOP_BASE_URL')) {
    define('THREEW_SHOP_BASE_URL', 'https://shop.3wdistributing.com/');
}

/**
 * Build the canonical shop URL, optionally seeded with catalog filters.
 *
 * @param string|array $search     Optional search term or array of terms.
 * @param array        $query_args Additional query parameters to merge.
 * @param string       $path       Optional path (e.g. product-category slug).
 *
 * @return string Fully-qualified shop URL.
 */
function threew_2025_get_shop_url($search = '', array $query_args = [], $path = '') {
    $base = rtrim(THREEW_SHOP_BASE_URL, '/') . '/';

    if ($path !== '') {
        $path = ltrim($path, '/');
        $base .= $path;
        if (substr($base, -1) !== '/') {
            $base .= '/';
        }
    }

    if (is_array($search)) {
        $search = array_filter(array_map('trim', $search));
        $search = array_map(static function ($term) {
            if ($term === '') {
                return $term;
            }

            if ($term[0] === '"' || $term[0] === "'" || strpos($term, ' ') === false) {
                return $term;
            }

            return '"' . $term . '"';
        }, $search);
        $search = implode(' ', $search);
    }

    $params = [];

    if ($search !== '' && $search !== null) {
        $params['s'] = $search;
        $params['post_type'] = 'product';
    }

    if (!empty($query_args)) {
        $params = array_merge($params, $query_args);
        if (!array_key_exists('post_type', $params)) {
            $params['post_type'] = 'product';
        }
    }

    if (empty($params)) {
        return $base;
    }

    return add_query_arg($params, $base);
}

/**
 * Theme setup.
 */
add_action('after_setup_theme', function () {
    add_theme_support('title-tag');
    add_theme_support('automatic-feed-links');
    add_theme_support('html5', ['comment-list', 'comment-form', 'search-form', 'gallery', 'caption', 'style', 'script', 'navigation-widgets']);
    add_theme_support('wp-block-styles');
    add_theme_support('woocommerce');
    add_theme_support('responsive-embeds');
    add_theme_support('editor-styles');
    add_theme_support('align-wide');
    add_theme_support('custom-logo', [
        'height'      => 120,
        'width'       => 300,
        'flex-height' => true,
        'flex-width'  => true,
    ]);

    register_nav_menus([
        'primary' => __('Primary Navigation', 'threew-2025'),
        'utility' => __('Utility Navigation', 'threew-2025'),
    ]);
});

/**
 * Helper to read asset manifest generated by @wordpress/scripts.
 */
function threew_2025_get_asset() {
    static $asset = null;

    if ($asset === null) {
        $asset_path = get_theme_file_path('build/index.asset.php');
        if (file_exists($asset_path)) {
            $asset = include $asset_path;
        } else {
            $asset = false;
        }
    }

    return $asset;
}

/**
 * Enqueue shared styles for both editor and frontend.
 */
add_action('enqueue_block_assets', function () {
    $style_path = get_theme_file_path('build/style-index.css');
    if (file_exists($style_path)) {
        wp_enqueue_style(
            'threew-2025-style',
            get_theme_file_uri('build/style-index.css'),
            [],
            filemtime($style_path)
        );
    }
});

/**
 * Enqueue theme scripts (frontend).
 */
add_action('wp_enqueue_scripts', function () {
    $asset = threew_2025_get_asset();
    $script_path = get_theme_file_path('build/index.js');
    $style_path  = get_theme_file_path('build/index.css');

    if ($asset && file_exists($script_path)) {
        wp_enqueue_script(
            'threew-2025-frontend',
            get_theme_file_uri('build/index.js'),
            $asset['dependencies'],
            $asset['version'],
            true
        );
    }

    if (file_exists($style_path)) {
        wp_enqueue_style(
            'threew-2025-frontend',
            get_theme_file_uri('build/index.css'),
            ['threew-2025-style'],
            filemtime($style_path)
        );
    }

    // Enqueue fitment selector view script for frontend interactivity
    $fitment_view_asset_path = get_theme_file_path('build/view.asset.php');
    $fitment_view_path = get_theme_file_path('build/view.js');

    if (file_exists($fitment_view_path) && file_exists($fitment_view_asset_path)) {
        $fitment_view_asset = include $fitment_view_asset_path;
        wp_enqueue_script(
            'threew-fitment-view',
            get_theme_file_uri('build/view.js'),
            $fitment_view_asset['dependencies'],
            $fitment_view_asset['version'],
            true
        );

        wp_localize_script(
            'threew-fitment-view',
            'threewShopConfig',
            [
                'baseUrl' => threew_2025_get_shop_url(),
            ]
        );
    }
});

/**
 * Enqueue block editor assets.
 */
add_action('enqueue_block_editor_assets', function () {
    $asset = threew_2025_get_asset();
    $script_path = get_theme_file_path('build/index.js');

    if ($asset && file_exists($script_path)) {
        wp_enqueue_script(
            'threew-2025-editor',
            get_theme_file_uri('build/index.js'),
            array_merge($asset['dependencies'], ['wp-edit-post']),
            $asset['version'],
            true
        );
    }
});

/**
 * Include fitment API endpoints
 */
require_once get_theme_file_path('inc/fitment-api.php');
