<?php
/**
 * 3W 2025 Theme bootstrap
 */

if (!defined('ABSPATH')) {
    exit;
}

/**
 * Theme setup.
 */
add_action('after_setup_theme', function () {
    add_theme_support('title-tag');
    add_theme_support('automatic-feed-links');
    add_theme_support('html5', ['comment-list', 'comment-form', 'search-form', 'gallery', 'caption', 'style', 'script', 'navigation-widgets']);
    add_theme_support('wp-block-styles');
    add_theme_support('responsive-embeds');
    add_theme_support('editor-styles');
    add_theme_support('align-wide');

    register_nav_menus([
        'primary' => __('Primary Navigation', 'threew-2025'),
        'utility' => __('Utility Navigation', 'threew-2025'),
    ]);
});

/**
 * Helper to read asset manifest generated by @wordpress/scripts.
 */
function threew_2025_get_asset() {
    static $asset = null;

    if ($asset === null) {
        $asset_path = get_theme_file_path('build/index.asset.php');
        if (file_exists($asset_path)) {
            $asset = include $asset_path;
        } else {
            $asset = false;
        }
    }

    return $asset;
}

/**
 * Enqueue shared styles for both editor and frontend.
 */
add_action('enqueue_block_assets', function () {
    $style_path = get_theme_file_path('build/style-index.css');
    if (file_exists($style_path)) {
        wp_enqueue_style(
            'threew-2025-style',
            get_theme_file_uri('build/style-index.css'),
            [],
            filemtime($style_path)
        );
    }
});

/**
 * Enqueue theme scripts (frontend).
 */
add_action('wp_enqueue_scripts', function () {
    $asset = threew_2025_get_asset();
    $script_path = get_theme_file_path('build/index.js');

    if ($asset && file_exists($script_path)) {
        wp_enqueue_script(
            'threew-2025-frontend',
            get_theme_file_uri('build/index.js'),
            $asset['dependencies'],
            $asset['version'],
            true
        );
    }
});

/**
 * Enqueue block editor assets.
 */
add_action('enqueue_block_editor_assets', function () {
    $asset = threew_2025_get_asset();
    $script_path = get_theme_file_path('build/index.js');

    if ($asset && file_exists($script_path)) {
        wp_enqueue_script(
            'threew-2025-editor',
            get_theme_file_uri('build/index.js'),
            array_merge($asset['dependencies'], ['wp-edit-post']),
            $asset['version'],
            true
        );
    }
});
